const data = [
  {
    id: 1,
    name: "Floral Printed Kurta Set",
    minOffer: 40,
    maxOffer: 90,
    image: "/images/1.jpg",
    price: 1200,
  },
  {
    id: 2,
    name: "Embroidered Anarkali",
    minOffer: 40,
    maxOffer: 75,
    image: "/images/2.jpg",
    price: 1100,
  },
  {
    id: 3,
    name: "Cotton Kurti",
    minOffer: 35,
    maxOffer: 70,
    image: "/images/3.jpg",
    price: 1000,
  },
  {
    id: 4,
    name: "Silk Saree Traditional",
    minOffer: 50,
    maxOffer: 80,
    image: "/images/4.jpg",
    price: 1300,
  },
  {
    id: 5,
    name: "Printed Lehenga Choli",
    minOffer: 45,
    maxOffer: 75,
    image: "/images/5.jpg",
    price: 1600,
  },
  {
    id: 6,
    name: "Straight Kurta Set",
    minOffer: 30,
    maxOffer: 60,
    image: "/images/5.jpg",
    price: 1500,
  },
  {
    id: 7,
    name: "Georgette Ethnic Gown",
    minOffer: 40,
    maxOffer: 70,
    image: "/images/7.jpg",
    price: 1900,
  },
  {
    id: 8,
    name: "Festive Sharara Suit",
    minOffer: 50,
    maxOffer: 80,
    image: "/images/8.jpg",
    price: 1700,
  },
  {
    id: 9,
    name: "Bandhani Print Kurti",
    minOffer: 35,
    maxOffer: 65,
    image: "/images/9.jpg",
    price: 1800,
  },
  {
    id: 10,
    name: "Chanderi Silk Kurta",
    minOffer: 30,
    maxOffer: 70,
    image: "/images/10.jpg",
    price: 2000,
  },
  {
    id: 11,
    name: "Designer Party Lehenga",
    minOffer: 55,
    maxOffer: 80,
    image: "/images/11.jpg",
    price: 2400,
  },
  {
    id: 12,
    name: "Casual Cotton Kurti",
    minOffer: 25,
    maxOffer: 60,
    image: "/images/12.jpg",
    price: 2200,
  },
  {
    id: 13,
    name: "Printed Ethnic Dress",
    minOffer: 30,
    maxOffer: 65,
    image: "/images/13.jpg",
    price: 2100,
  },
  {
    id: 14,
    name: "Wedding Wear Saree",
    minOffer: 50,
    maxOffer: 85,
    image: "/images/14.jpg",
    price: 2300,
  },
  {
    id: 15,
    name: "Indo-Western Fusion",
    minOffer: 40,
    maxOffer: 75,
    image: "/images/15.jpg",
    price: 2500,
  },
  {
    id: 16,
    name: "Embroidered Kurta",
    minOffer: 35,
    maxOffer: 70,
    image: "/images/16.jpg",
    price: 2900,
  },
  {
    id: 17,
    name: "Festive Silk Anarkali",
    minOffer: 50,
    maxOffer: 80,
    image: "/images/17.jpg",
    price: 2700,
  },
  {
    id: 18,
    name: "Printed Maxi Ethnic",
    minOffer: 30,
    maxOffer: 60,
    image: "/images/1.jpg",
    price: 2800,
  },
  {
    id: 19,
    name: "Traditional Dhoti Kurta",
    minOffer: 40,
    maxOffer: 70,
    image: "/images/2.jpg",
    price: 2240,
  },
  {
    id: 20,
    name: "Festive Jacket Style",
    minOffer: 45,
    maxOffer: 75,
    image: "/images/3.jpg",
    price: 2345,
  },
];

export default data;
